server:
  port: 8085

spring:
#  main:
#    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/smile
    username: root
    password: mysqlroot
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: "vs2mRgF7UBwq8GqUMzvv49vYL6xhuDSDuy5NHzF4zxs="
  expiration: 180000 # 3 minutes in milliseconds

env:
  version: 1.xx



#  adminPassword: admin
#  staffPassword: staff
