server:
  port: 3000

spring:
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:mysql-2864a21c-nikshithaaella123-f862.e.aivencloud.com}:${DATABASE_PORT:22552}/${DATABASE_NAME:defaultdb}
    username: ${DATABASE_USER:avnadmin}
    password: ${DATABASE_PASSWORD:AVNS_56a08aepn1s4xTtuJIc}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    locations:
      - classpath:db/migration
    messages:
      basename: il8n/messages
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: "vs2mRgF7UBwq8GqUMzvv49vYL6xhuDSDuy5NHzF4zxs="
  expiration: 180000 # 3 minutes in milliseconds

env:
  version: 1.xx


#  adminPassword: admin
#  staffPassword: staff
